config/routes.rb
Rails.application.routes.draw do
  get 'invitations/new'

  get 'invitations/create'

  root                  'basic_pages#home'

  get 'contact' =>  'basic_pages#contact'

  get 'about'    =>  'basic_pages#about'
  
  get 'faq'     =>  'basic_pages#faq'
  
  get 'signup'  => 'users#new'
  
  get 'howitworks' => 'basic_pages#howitworks'
  
  get 'newbiz' => 'businesses#new'
  
  get 'login'  => 'sessions#new'
  
  post 'login'   =>   'sessions#create'
  
  delete 'logout'   =>   'sessions#destroy'
  
  post 'users/set_geolocation' => 'users#set_geolocation'
  
  post 'users/business_index' => 'users#business_index'
  
  get 'manager' => 'users#manager'
  
  get 'feedback' => 'users#feedback'
  
  get 'joinlist' => 'invitations#joinlist'
  
  resources :users
  
  resources :businesses
  
  resources :vip_codes
  
  get 'vipcode' => 'vip_codes#new'
  
  resources :reviews, only: [:create, :destroy]
  
  get 'instructreview' => 'reviews#instructreview'
  
  get "vipcode" => 'invitations#vipcode'
  
  get 'feedback' => 'reviews#feedback'
  
  resources :invitations
  

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
    before_action :admin_user, only: [:new, :create, :update, :edit]
  
  
 def index
   @user = current_user
   @businesses = Business.near([current_user.latitude, current_user.longitude], 0.25)
 end
 
 def edit
  @business = Business.find(params[:id])
 end
 
 def update
    @business = Business.find(params[:id])
    if @business.update_attributes(business_params)
      flash[:success] = "Business updated"
      redirect_to @business
    else
      render 'edit'
    end
 end
 
 
  def show
  @business = Business.find(params[:id])
  @users = @business.users
  end
  
    def create
    @business = Business.new(business_params)
     if @business.save
       flash[:success] = "Business created"
       redirect_to @business
     else
       render 'new'
     end
    end
  
  def new
   @business = Business.new
  end
  
  
  
  private
  
  def business_params
   params.require(:business).permit(:name, :address, :sector, :latitude, :longitude)
  end
  
    #confirms an admin user
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    #confirms a manager
    def manager_user
      redirect_to(root_url) unless current_user.manager?
    end
  
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business.html.erb
<li id="business-<%= business.id %>">
    - <%= link_to business.name, business %> - 
</li>

app/views/businesses/edit.html.erb
<% provide(:title, 'Edit Business') %>
<h1 class="pageheader">Edit Business</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@business) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form_control' %>
            
            <%= f.label :address %>
            <%= f.text_field :address, class: 'form_control' %>
            </br>
            </br>
            
            <%= f.label :sector, "Type of Business" %>
            <%= f.select :sector, options_for_select(%w[-- Salon Gym PT Other]), class: 'form_control' %>
            
            </br>
            </br>
            <%= f.submit "Edit Business", class: "btn btn-primary2" %>
        <% end %>
    </div>
</div>

app/views/businesses/index.html.erb
<% provide(:title, 'Find Five Members') %>
</br>
<h1 class="pageheader">Find a Five Salon</h1>
</br>

<% if @businesses.empty? %>
<h3>Unfortunately there are no Five Salons near you yet.</h3>
</br>
<h3>If you have a comment about an employee, just send an email to <a href="mailto:team@fiveme.io?Subject=Hey%20Five%20team!">team@fiveme.io</a> with the name of the salon and employee.</h3>
</br>
<h3>We can make sure they get to keep that review once they join Five!</h3>

<% else %>
<ol class="business">
    <% @businesses.each do |business| %>
    <li>
         <%= link_to business.name, business %> 
    </li>
    <% end %>
</ol>
<% end %>
</br>
</br>
</br>
<div class="map">
<iframe width="600" height="450" frameborder="0" 
style="border:0" 
src="https://www.google.com/maps/embed/v1/search?q=<%= current_user.latitude %>%20<%= current_user.longitude %>&key=AIzaSyClueDRPj-vQsJ7paz_lh5AaNwSxANxoQE">
</iframe>
</div>
</br>
</br>
</br>

app/views/businesses/new.html.erb
<% provide(:title, 'New Business') %>
<h1 class="pageheader">Create a New Business</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@business) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form_control' %>
            
            <%= f.label :address %>
            <%= f.text_field :address, class: 'form_control' %>
            </br>
            </br>
            
            <%= f.label :sector, "Type of Business" %>
            <%= f.select :sector, options_for_select(%w[-- Salon Gym PT Other]), class: 'form_control' %>
            
            </br>
            </br>
            <%= f.submit "Create new business", class: "btn btn-primary2" %>
        <% end %>
    </div>
</div>

app/views/businesses/show.html.erb
<% provide(:title, @business.name) %>
<h1 class="pageheader">
   <%= @business.name %>'s 
   </br>
   Five Members (<%= @business.users.count %>)
</h1>

<h2><%= Geocoder.search(@business.address).first.city %>, <%= Geocoder.search(@business.address).first.state %></h2>
<% if current_user.admin? %>
<h3><%= link_to "Edit Business", edit_business_path %></h3>
<% end %>
</br>
<p class="plsfeed">Please give your feedback!</p>
</br>


<ul class="users">
    <%= render @users %>
</ul>