config/routes.rb
Rails.application.routes.draw do
  get 'invitations/new'

  get 'invitations/create'

  root                  'basic_pages#home'

  get 'contact' =>  'basic_pages#contact'

  get 'about'    =>  'basic_pages#about'
  
  get 'faq'     =>  'basic_pages#faq'
  
  get 'signup'  => 'users#new'
  
  get 'howitworks' => 'basic_pages#howitworks'
  
  get 'newbiz' => 'businesses#new'
  
  get 'login'  => 'sessions#new'
  
  post 'login'   =>   'sessions#create'
  
  delete 'logout'   =>   'sessions#destroy'
  
  post 'users/set_geolocation' => 'users#set_geolocation'
  
  post 'users/business_index' => 'users#business_index'
  
  get 'manager' => 'users#manager'
  
  get 'feedback' => 'users#feedback'
  
  get 'joinlist' => 'invitations#joinlist'
  
  resources :users
  
  resources :businesses
  
  resources :vip_codes
  
  get 'vipcode' => 'vip_codes#new'
  
  resources :reviews, only: [:create, :destroy]
  
  get 'instructreview' => 'reviews#instructreview'
  
  get "vipcode" => 'invitations#vipcode'
  
  get 'feedback' => 'reviews#feedback'
  
  resources :invitations
  

end

app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  
  def home
  end

  def contact
  end

  def about
  end
  
  def faq
  end
  
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/views/basic_pages/about.desktop.erb
<% provide(:title, "About") %>
</br>
</br>
</br>
</br>
</br>
    <h1 class="pageheaderD">About</h1>
    </br>
               <p style="color:#d5706f; font-style:italic">
         Five turns client feedback into meaningful review scores to use for professional promotion. 
        </p>
        </br>
        </br>

        <p>
            When you review someone on Five, you can be confident that your feedback is helping change someone's career and life. It contributes to a professional metric that they can use.
       
         Until now, recommendations from clients were either stuck on Yelp, a simple 1-5 star rating, or both! 
       
        With Five, your reviews belong to you. They are formulated to produce a meaningful rating score that you can use to get new clients, promotions, and jobs. It's a new line for your resume.
        </p>
        </br>
        
        
        </br>
        
        </br>

          </br>
          </br>
          </br>
          </br>
          
<div id="homeemploybizD">  
</br>
</br>
</br>
<h1><span class="glyphicon glyphicon-briefcase"></span></h1>
<h3>Professionals</h3>
</br>
<p>Use your reviews to help acquire new customers or earn that next promotion.</p>
<br>
<p>Collect and own your own data - <b>reviews about you should belong to you.</b></p>
</br>
</br>
</br>
</br>
</div>
</br>
</br>
</br>

<div id="homecustomersD">
</br>
</br>
<h3><span class="glyphicon glyphicon-user"></span><span class="glyphicon glyphicon-user"></span><span class="glyphicon glyphicon-user"></span></h3>
<h3>Customers</h3>
</br>
<p>Quickly and easily leave feedback for your barber or stylist for them to use for professional promotion.</p> 
</br>
</br>
<p>No more “staying on the line” or entering a 25+ digit code online to submit your feedback without any idea of how it is used. </p>
</br>
</br>
</br>

</div>
</br>
</br>
<div id="homeemploybizD"> 
</br>
</br>
<span class="glyphicon glyphicon-home"></span>
<h3>Businesses</h3>
</br>
<p>Stop spending time and money on feedback surveys that produce minimal data.</p>
</br>
<p>Start making informed decisions in a labor market that is difficult to navigate.</p>
</br>
</br>
</div>
</br>
</br>
</br>
  

app/views/basic_pages/about.html.erb
<% provide(:title, "About") %>

    <h1 class="pageheader">About Five</h1>
        <p style="color:#d5706f; font-style:italic">
         Five turns client feedback into meaningful review scores to use for professional promotion. 
        </p>
        </br>

        <p>
            When you review someone on Five, you can be confident that your feedback is helping change someone's career and life. It contributes to a professional metric that they can use.
        </p>
        </br>
        <p>
         Until now, recommendations from clients were either stuck on Yelp, a simple 1-5 star rating, or both! 
        </p>
        </br>
        
        
        <p>
        With Five, your reviews belong to you. They are formulated to produce a meaningful rating score that you can use to get new clients, promotions, and jobs. It's a new line for your resume.
        </p>
        </br>
        
        
        </br>
        
        </br>
    
        <p>
        <% if logged_in? %>
         Thanks for using Five!
         <% else %>
         <%= link_to "Get on Five Today!", signup_path %>
         <% end %>
        </p>
          </br>
          </br>

app/views/basic_pages/contact.desktop.erb
<% provide(:title, "Contact") %>
</br>
</br>
</br>
</br>
</br>
    <h1 class="pageheaderD">Contact</h1>
    </br>
    <div id="homeemploybizD">
    </br>
    </br>
    </br>
        <p>
        If you have any questions or comments about Five send us an email at <a href="mailto:team@fiveme.io?Subject=Hey%20Five%20team!">team@fiveme.io</a>
        </br>
        </p>
        </br>
        </br>
        </br>
    
        </div>

app/views/basic_pages/contact.html.erb
<% provide(:title, "Contact") %>

    <h1 class="pageheader">Contact</h1>
        <p>
        If you have any questions or comments about Five send us an email at <a href="mailto:team@fiveme.io?Subject=Hey%20Five%20team!">team@fiveme.io</a>
        </br>
        </p>
        </br>
 

app/views/basic_pages/faq.desktop.erb
<% provide(:title, "FAQ") %>
</br>
</br>
</br>
</br>
</br>
    <h1 class="pageheaderD">Frequently Asked Questions</h1>
    </br>
    </br>
    <div class="faqdivD">
        <p class="faqD">
        What am I supposed to do with Five?
        </p>
        <p>
        You can rate wellness professionals  who helped you (trainers, salon professionals, physical therpists, etc) or collect ratings from your clients.
        </br>
        </br>
        If you manage a business, you can use Five to track customer satisfaction and evaluate talent.
        </p>
        </br>
        </br>
        </br>

        <p class="faqD">
        How does I become a Five member? 
        </p>    
        <p>
        We're still in a beta stage, so our user list is small and only by invitation (at the moment!). Just send us an email at <a href="mailto:newMember@fiveme.io?Subject=Get%20me%20on%20Five!">newMember@fiveme.io</a> saying why you would like to join, and we'll take care of the rest.
        </br>
        </br>
        At Five we are hyper-aware of data integrity--we strive to show off and accurately represent your reputation. That's our mission and we take it very seriously.
        </br>
        </br>
        An automated web-based verification process is being built, but for now we will take care of this offline. 
        </p>
        </br>
        </br>
        </br> 
        <p class="faqD">
         How do I, as an employee, become affiliated with a business? 
        </p> 
        <p>
            When you sign up, you have an option to put in the <u>Business ID #</u> associated with your place of work, which you can get from your colleagues, a manager or request from <a href="mailto:newMember@fiveme.io?Subject=Get%20me%20on%20Five!">newMember@fiveme.io</a>
        </br>
        </br>
        You can also add or change this <u>Business ID #</u> at any time by editing your profile.
        </p>
       </br>
       </br>
       </br>
        <p class="faqD">Why is Five only available through mobile devices? Why can't I access Five on my desktop?</p>
        <p>
        At Five, we want to make it as easy and simple as possible to leave reviews for all the great people you interact with. </p>
        </br>
        </br>
        <p>Did you have a great stylist, or barber or manicurist? If you think he/she deserves to be recognized for that, Five makes it incredibly easy for you to find that employee using the location data from your phone and to help give him/her that recognition on the spot.</p>
        </br>
        </br>
        <p>Waiting until you go home means having to manually search for that great employee and makes leaving a review an additional chore in your day. We want to keep it simple and easy to give great people the recognition they deserve.</p></p>
        </br>
        </br>
        
        </div>
        </br>
        </br>
        </br>

app/views/basic_pages/faq.html.erb
<% provide(:title, "FAQ") %>

    <h1 class="pageheader">Frequently Asked Questions</h1>
    </br>
        <p class="faq">
        What am I supposed to do with Five?
        </p>
        <p>
        You can rate salon professionals who helped you (hair stylists, barbers, manicurists, etc) or collect ratings from your clients.
        </br>
        </br>
        If you manage a salon, you can use Five to track customer satisfaction and evaluate talent.
        </p>
        </br>
        </br>

        <p class="faq">
        How does my salon become a Five member? 
        </p>    
        <p>
        Simply send us an email at <a href="mailto:newMember@fiveme.io?Subject=Get%20me%20on%20Five!">newMember@fiveme.io</a> and we'll take care of the rest.
        </br>
        </br>
        At Five we are hyper-aware of data integrity--we strive to show off and accurately represent your reputation. That's our mission and we take it very seriously.
        </br>
        </br>
        An automated web-based verification process is being built, but for now we will take care of this offline. 
        </p>
        </br>
        </br>
    <p class="faq">
         How do I, as an employee, become affiliated with a salon? 
        </p> 
        <p>
        When you sign up, you have an option to put in a <u>Business ID #</u> associated with your business, which you can get from your colleagues, a manager or request from <a href="mailto:newMember@fiveme.io?Subject=Get%20me%20on%20Five!">newMember@fiveme.io</a>
        </br>
        </br>
        You can also add or change this <u>Business ID #</u> at any time by editing your profile.
        </p>
       </br>
       </br>
      
        

app/views/basic_pages/home.desktop.erb
<head>
<style>
  background {color:#EF5350}
  h1   {color:#5C6BC0}
  h2   {color:#5C6BC0}
  h3   {color:#5C6BC0}
  p    {color:#747474}
</style>
</head>

<div class="homeheadD">
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<h2 id="taglineD">Claim your professional reputation</p>
</br>
</br>
</br>

<h2 id="tagline2D">Five is a web and mobile platform for wellness professionals to collect feedback from clients. Five turns that feedback into meaningful review scores to use for professional promotion.</h2>
</br>
</br>

</br>
</br>
<h3><%= link_to image_tag("trainerpt_2-iphone-left.original.png", alt: "Five screenshot"), root_path %></h3>
<!---<h3 id="or2D">We are a mobile only platform (please see <%= link_to "FAQ", faq_path %> for why!)
</br>
</br>
</br>
Visit www.FiveMe.io from a mobile device to start using Five today!</h3> --->
</br>
</br>
</br>


<%= form_for Invitation.new do |f| %>
 
  <%= f.text_field :recipient_email, :placeholder => 'Email here, please' %>
  </br>
<%= f.submit 'Join the waitlist', class: "btn btn-primary2d" %>

<% end %>


</br>
</br>
</br> 
</br>
</br>
</br>
</br>
</br>


</br>
</br>
</br>
</br>
</br>
</br> 
</br>
</br>
</br>

</div>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58772031-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/basic_pages/home.html.erb
<head>
<style>
  background {color:#EF5350}
  h1   {color:#5C6BC0}
  h2   {color:#5C6BC0}
  h3   {color:#5C6BC0}
  p    {color:#747474}
</style>
</head>

<div class="homehead">

</br>
</br>
</br>

<h2 id="tagline">Claim your professional reputation</p>
</br>
</br>

<h2 id="tagline2">Five is a web and mobile platform for wellness professionals to collect feedback from clients. Five turns that feedback into meaningful review scores to use for professional promotion.</h2>
</br>

<% if logged_in? %>


 </br>
 </br>
 </br>
 </br>
 </br>
 </br>
<%= link_to "Log out", logout_path, method: "delete", class: "btn btn-primary center-block" %>
</br>
</br>
</br>
</br>
</br>
<% else %>
</br>
<%= link_to "Log in", login_path, class: "btn btn-primary center-block" %>
</br>
<p id="or">Or</p>
</br>
<%= link_to "Sign Up", vipcode_path, class: "btn btn-primary center-block" %>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<% end %>

</br>
</br>
</br>
</div>


<div id="homeemploybiz">  
</br>
</br>

<h3><%= image_tag("user2b.png", alt: "Current User") %></h3>
<h3 class="home_titles">Salon Professionals</h3>
<p class="home_p">Use your reviews to help acquire new clients or earn that next promotion.</p>
<br>
<p class="home_p">Collect and own your own data - reviews about you should belong to you. </p>
</br>

</br>
</div>

<div id="homecustomers">
</br>
</br>
<h3><%= image_tag("usersb.png", alt: "Users") %></h3>
<h3 class="home_titles">Customers</h3>
<p class="home_p">Quickly and easily leave feedback for your barber or stylist for them to use for professional promotion.</p> 
</br>
<p class="home_p">No more “staying on the line” or entering a 25+ digit code online to submit your feedback without any idea of how it is used.</p>
</br>
</br>
</div>

<div id="homeemploybiz"> 
</br>
</br>
<h3><%= image_tag("officeb.png", alt: "Businesses") %></h3>
<h3 class="home_titles">Salons and Beauty Schools</h3>
<p class="home_p">Stop spending time and money on feedback surveys that produce minimal data.</p>
</br>
<p class="home_p">Start making informed decisions in a labor market that is difficult to navigate.</p>
</br>
</br>

</div>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58772031-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/basic_pages/howitworks.html.erb
<% provide(:title, "How it works") %>

    <h1 class="pageheader">How does Five work?</h1>
    </br>
        <p class="faq">
        What is Five? How will I use it?
        </p>
        <p>
        Five is the easiest way to get feedback from clients and turn it into something meaningful.
        </br>
        </br>
        It's a straightforward platform to ask your clients 3 questions:
        </br>
        -  "How was your experience?"
        </br>
        -  "How were my skills?"
        </br>
        -  "Did we get along?"
        </p>
        <br>
        <br>
        <p>
        These are the 3 questions that tell us most about a customer's experience.
        </p>
        </br>

        <p class="faq">
        So what? Some clients answer 3 questions, how does that help anyone? 
        </p>    
        <p>
        We can tell quite a bit from analyzing the different patterns in responses to those questions. And we gain even more insight by looking at the rate at which clients give feedback.
        </br>
        </br>
        After that analysis, we compile this into a score out of 500 which you can use to actually prove your talent to future clients and salons.
        
       
         
        </p>
        </br>
        </br>
    <p class="faq">
         How do I get my score? 
        </p> 
        <p>
          For now, you can simply request it from us by sending an email to <a href="mailto:my500@fiveme.io?Subject=Get%20me%20on%20Five!">my500@fiveme.io</a>
          </br>
          </br>
          We will be happy to send regular reports as well--always 100% for free.
          </br>
          </br>
        We are in the process of building tools for you to see your score, promote your score, and show off other fun metrics around how you are trending.
        </br>
      
        </p>
        </br>
        </br>
        <p>
            If there are any questions, please don't hesitate to drop us an email!
        </p>
       </br>
       </br>
      
        