config/routes.rb
Rails.application.routes.draw do
  get 'invitations/new'

  get 'invitations/create'

  root                  'basic_pages#home'

  get 'contact' =>  'basic_pages#contact'

  get 'about'    =>  'basic_pages#about'
  
  get 'faq'     =>  'basic_pages#faq'
  
  get 'signup'  => 'users#new'
  
  get 'howitworks' => 'basic_pages#howitworks'
  
  get 'newbiz' => 'businesses#new'
  
  get 'login'  => 'sessions#new'
  
  post 'login'   =>   'sessions#create'
  
  delete 'logout'   =>   'sessions#destroy'
  
  post 'users/set_geolocation' => 'users#set_geolocation'
  
  post 'users/business_index' => 'users#business_index'
  
  get 'manager' => 'users#manager'
  
  get 'feedback' => 'users#feedback'
  
  get 'joinlist' => 'invitations#joinlist'
  
  resources :users
  
  resources :businesses
  
  resources :vip_codes
  
  get 'vipcode' => 'vip_codes#new'
  
  resources :reviews, only: [:create, :destroy]
  
  get 'instructreview' => 'reviews#instructreview'
  
  get "vipcode" => 'invitations#vipcode'
  
  get 'feedback' => 'reviews#feedback'
  
  resources :invitations
  

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#footer-body">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="footer-body">
                <ul class="nav navbar-nav">
                    <% if logged_in? %>
                    <li>
                        <ul class="footericons">
                            <li> <%= link_to image_tag("feedbubble.png", alt: "Current User"), instructreview_path %></li>
                            <li><%= link_to "Get Feedback", instructreview_path, class: "btn btn-primary3 center-block" %></li>
                        </ul>
                    </li>
                    <li>
                    <ul>
                      
                   
                    </ul>
                    </li>
                    <li>
                        <ul class="footericons">
                            <li> <%= link_to image_tag("user2.png", alt: "Profile"), current_user %></li>
                            <li><%= link_to "My Score", current_user, class: "btn btn-primary3 center-block" %></li>
                        </ul>
                    </li>
                    <% else %>
                    
                    <li>
                        <ul class="footericons">
                             <li> <%= link_to image_tag("info.png", alt: "About"), about_path %></li>
                            <li><%= link_to "About", about_path %></li>
                        </ul>
                    </li>
                    
                    <li>
                        <ul class="footericons">
                             <li> <%= link_to image_tag("envelope.png", alt: "Contact"), contact_path %></li>
                            <li><%= link_to "Contact", contact_path %></li>
                        </ul>
                    </li>
                    
                    <li>
                        <ul class="footericons">
                             <li> <%= link_to image_tag("question.png", alt: "FAQ"), faq_path %></li>
                            <li><%= link_to "FAQ", faq_path %></li>
                        </ul>
                    </li>
                    
                    <% end %>
                            
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.desktop.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to image_tag("FiveLogo_white_wro_d.png", alt: "Five logo"), root_path, id: "logoD" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
          
                  <li class="deskItems"><%= link_to "About", about_path %></li>
                  <li class="deskItems"><%= link_to "Contact", contact_path %></li>
                  <li class="deskItems"><%= link_to "FAQ", faq_path %></li>
 
              </ul>
        </nav>
      </div>
  </header>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="container">
        <%= link_to image_tag("FiveLogo_white_wro_small.png", alt: "Five logo"), root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= image_tag("hamburger.png", alt: "menu icon") %>
                </a>
                <ul class="dropdown-menu pull-left">
                 <% if logged_in? %>
                 
                 
                 <% if current_user.manager? %>
                 <li><%= link_to "Manager", manager_path %></li>
                 
                 <% if (current_user.invitation_limit > 0) %>
                 <li><%= link_to "Invite (" + current_user.invitation_limit.to_s + ")", new_invitation_path %></li>
                 <% end %>
                 <li> 
                 <% if current_user.admin? %>
                 <%= link_to "Search", "#", :id => 'findMe' %>
                <script>
                  $(function(){
                     $("a#findMe").click(function(){
                         if (navigator.geolocation) {
                             navigator.geolocation.getCurrentPosition(function (position) {
                                 $.post('/users/set_geolocation/', {latitude: position.coords.latitude,
                                             longitude: position.coords.longitude,
                                             dataType: 'float'});
                             }, function () {
                                 alert('We couldn\'t find your position.');
                             });
                         } else {
                             alert('Your browser doesn\'t support geolocation.');
                         }
                      });
                  })
                </script>
               </li>
               <% end %>
                <% end %>
                 
                  
                  <li><%= link_to "Feedback", instructreview_path %></li>
                  <li><%= link_to "Huh?", howitworks_path %></li>
                  
                  <% if current_user.admin? %>
                  <li><%= link_to "Create Biz", newbiz_path %></li>
                  
                  <% end %>
                  <li><%= link_to "About", about_path %></li>
                  
                  <li><%= link_to "Contact", contact_path %></li>
                  
                  <li><%= link_to "FAQ", faq_path %></li>
                  
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                  <% else %>
                  <li><%= link_to "About", about_path %></li>
                  
                  <li><%= link_to "Contact", contact_path %></li>
                  
                  <li><%= link_to "FAQ", faq_path %></li>
                  
                  <li><%= link_to "Log in", login_path %></li>
                  <% end %>
              </ul>
          </li>

            
          </ul>
        </nav>
      </div>
  </header>

app/views/layouts/_shim.desktop.erb
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax.libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax.libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'custom', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'circle-progress' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/layouts/desktop_application.desktop.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'desktop', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>